Repository BlitzKomodo/Dogma, pull requests merged in 2024-03, with the labels that each got.

#5 changed main return val to n+1
  main.py
Labels: feature

#9 changing it again :/
  main.py
Labels: QA

#10 fixing up the concatenation issue
  main.py
Labels: bug

#14 feaure_issue12 : n = 3001
  main.py
Labels: feature

#16 N + 3 to N
  main.py
Labels: hotfix

#17 added the super_(x) function
  main.py
Labels: feature
